### ISSUE TITLE
Distorted lounge-music when connecting with mono client

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#11]
I think connecting both stereo outputs of the lounge-music to a single mono send is overloading the channel. Maybe mono clients just have to accept one channel of the lounge-music? I can do a PR if you agree.

https://github.com/madwort/jacktrip_pypatcher/blob/8e42a56b4c4ac9a4980e8bf56dc4544c5243852b/jack_client_patching.py#L64-L68

I guess we'll have the same problem during sessions though, however that might need a smarter solution...

**Comment by madwort** [comment]
Hmmm, interesting - it's certainly possible, & I'm happy to send a single mono send of the lounge-music, but are there implications elsewhere where we do similar things?

**Comment by sandreae** [comment]
Yeh, I think the same thing might happen when we sum a stereo clients signal to a mono client. Is this something that will just have to be managed on the client side, by turning down the (stereo clients) input gain if anyone is receiving a distorted signal? Do you know how JackTrip in hub-mode manages this scenario?
