### ISSUE TITLE
Mono client patching error

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#23]
Now that by default we assume a client is stereo, if they actually connect in mono then an error occurs when we attempt to connect their `send_2` or `receive_2`. Need to wrap all examples of the below in `try:` statements.

https://github.com/noiseorchestra/jacktrip_pypatcher/blob/beefd3406984d2d096b0b47c19760ed0041d01b2/jack_client_patching.py#L70-L77

**Comment by madwort** [comment]
Yeah, I'm wondering if this needs refactoring to test whether the port exists & then patching accordingly, rather than attempting to patch & catching the exception when it fails.

**Comment by sandreae** [comment]
Yeh, I agree. I'm happy to have a go at this in a few weeks. After we've done a few sessions as it is now and are sure stereo first is the way we want to go.
