### ISSUE TITLE
How does the ladspa plugin pan stereo clients?

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#24]
Looking at using the ladspa plugin to pan all clients but need to be clear how the plugin actually pans the ports. 

For a plugin with these settings:

`$NG_JACKSPA_PATH/jackspa-cli -j left-50 -i '0:0:0:-0.5:0:0' /usr/lib/ladspa/inv_input.so 3301`

If a stereo client is connected to this plugin, do it's left and right channels both get panned to exactly -0.5 left, or do they both move -0.5 to the left, retaining some stereo separation? 

This has implications on how the plugins should be used.

**Comment by madwort** [comment]
As it's open-source, we can check out the source code! Here:

https://bazaar.launchpad.net/~invada/invada-studio/ladspa/view/head:/inv_input.c#L157

so looks like we have (simplified version):

```
        fPan       = plug->ConvertedPan;
        ....
	fLPan=1-fPan;
	fRPan=1+fPan;
        ...
        for (lSampleIndex = 0; lSampleIndex < SampleCount; lSampleIndex++) {
                fAudio1 =  *(pfAudioInput1++) ;
		fAudio2 = *(pfAudioInput2++) ;

                fAudio1 *= fLPan;
		fAudio2 *= fRPan;

		*(pfAudioOutput1++) = fAudio1;
		*(pfAudioOutput2++) = fAudio2;
        }
```

Does that answer your question?

**Comment by madwort** [comment]
actually, looks like if width is not set to `0` then it might be able to do what you want? 

https://bazaar.launchpad.net/~invada/invada-studio/ladspa/view/head:/inv_input.c#L202

```
		if(fWidth<=0) {
			fMono = (fAudio1 + fAudio2) / 2;
			fAudio1 = (1+fWidth)*fAudio1 - fWidth*fMono;
			fAudio2 = (1+fWidth)*fAudio2 - fWidth*fMono;
		} else {
			fStereoL = (fAudio1 - fAudio2) / 2;
			fStereoR = (fAudio2 - fAudio1) / 2;
			fAudio1 = (1-fWidth)*fAudio1 + fWidth*fStereoL;
			fAudio2 = (1-fWidth)*fAudio2 + fWidth*fStereoR;
		}
```

**Comment by sandreae** [comment]
Thanks! 

I was looking through this, but was taking a while to home in on the useful info....

Just wanna check I'm understanding this correctly. It looks like by default it works like a mixing desk (makes sense!) and if you pan a client fully left, you lose anything in the right channel.

However, if we try setting width to `> 0` then it may retain left and right signals, moving both across the overall stereo field.

Sound right? I can experiment a little if so, it would be quite cool for panning stereo clients.

**Comment by madwort** [comment]
> Just wanna check I'm understanding this correctly. It looks like by default it works like a mixing desk (makes sense!) and if you pan a client fully left, you lose anything in the right channel.

I don't actually know how a mixing desk works, but yeah if you `pan -1, width 0` your input `{A,B}` will turn into output `{A*1,B*0}` => `{A,0}`.   `pain 0.5, width 0` will output `{A*0.5, B*1.5}`?

> However, if we try setting width to `> 0` then it may retain left and right signals, moving both across the overall stereo field.

Actually I just re-read it, and I think the pan is applied before the width setting, so if you pan -1/1 & lose the other channel then width would just be adding back in some silence - so wouldn't do what you need.

**Comment by sandreae** [comment]
> Actually I just re-read it, and I think the pan is applied before the width setting, so if you pan -1/1 & lose the other channel then width would just be adding back in some silence - so wouldn't do what you need.

Oh ye, of course.... 

Ok, good to know this is how it works though. Will think on.

Thanks.

**Comment by madwort** [comment]
is this fixed now? can we close this ticket?
