### ISSUE TITLE
Move connect code out of autopatch & into helper functions for 1/2/3 clients

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#31]
Think it might be nice to move these blocks (e.g. [this block for one client](https://github.com/noiseorchestra/jacktrip_pypatcher/blob/trunk/jacktrip_pypatcher.py#L128-L151) ) into its own helper function, to reduce the length of `autopatch()` and make it more wieldy...

**Comment by madwort** [comment]
(I don't mind doing this, if I can find the time...)

**Comment by sandreae** [comment]
I started looking into this and ended up having to pass around a tonne of arguments between functions (all_ladspa_plugins, jacktrip_clients, darkice_port etc...).

I wondered if a nice solution would be to have a data class which is initiated in main() and then passed into autopatch. Has the added benefit of neatly declaring all our session variables in the same place.

Something like this:

```
class PypatcherParams:
    def __init__(self, darkice_prefix, hold_music_port, jacktrip_clients,
                 all_panning_positions, max_supported_clients):
        self.darkice_prefix = darkice_prefix,
        self.darkice_port = None,
        self.hold_music_port = hold_music_port,
        self.jacktrip_clients = jacktrip_clients,
        self.all_panning_positions = all_panning_positions,
        self.all_ladspa_ports = None,
        self.max_supported_clients = max_supported_clients

```
Initiated like so:

```
    params = PypatcherParams(
        darkice_prefix="darkice",
        hold_music="lounge-music",
        jacktrip_clients=jacktrip_clients,
        all_panning_positions=[0, -0.15, 0.15, -0.3, 0.3, -0.45,
                               0.45, -0.6, 0.6, -0.75, 0.75],
        max_supported_clients=11)

    params.darkice_port = pypatcher_helpers.get_darkice_port(
        jackClient, dry_run, params.darkice_prefix)
    params.all_ladspa_ports = jackClient.get_ports("ladspa-.*")
```

I wondered if this could all be attached to `jack_client_patcher`, haven't thought through if that makes sense though. What do you think?

**Comment by madwort** [comment]
hmm, yeah, a refactor to encapsulate some stuff in (a class|classes) would definitely be good, needs some thought though. Obviously the classic object-oriented class thing might ideally mean creating multiple classes to encapsulate the relevant pieces of data alongside the related code - e.g. a `darkice` class/object instance that knows its prefix/port; a `ladspa` class/object that is instantiated with the list of panning positions etc; and then have a PyPatcher class that allows you to access the `darkice` object, the `ladspa` object, etc...

**Comment by sandreae** [comment]
Nice! Shall I re-write https://github.com/noiseorchestra/jacktrip_pypatcher/pull/32 following the same method?

**Comment by madwort** [comment]
yeah, sounds good.

**Comment by madwort** [comment]
(could you review the darkice PR & merge if you like?)

**Comment by sandreae** [comment]
> (could you review the darkice PR & merge if you like?)

I'd rather not start merging stuff into `trunk` until after the session on Tues as I don't have any time for testing before then. I know that's being extra cautious... I thought we could start a new dev branch which we can merge all this refactoring into. Agree?

**Comment by sandreae** [comment]
> > (could you review the darkice PR & merge if you like?)
> 
> I'd rather not start merging stuff into `trunk` until after the session on Tues as I don't have any time for testing before then. I know that's being extra cautious... I thought we could start a new dev branch which we can merge all this refactoring into. Agree?

(also, are you admin for this repo? I thought I fixed that a while ago?)

**Comment by madwort** [comment]
We should start doing releases! That way you can use switch to a tested release for the session, and keep track of everything! Go here to do a release: 

https://github.com/noiseorchestra/jacktrip_pypatcher/releases/new

**Comment by madwort** [comment]
Yeah, I'm an admin, for me part of collaborating like this is the giving & receiving of reviews - it shouldn't be me reveiewing you, we both review each other!

**Comment by madwort** [comment]
But yeah, you could just make a note of the commit id of the version of the code you want to use for the session & checkout that!

**Comment by sandreae** [comment]
> Yeah, I'm an admin, for me part of collaborating like this is the giving & receiving of reviews - it shouldn't be me reviewing you, we both review each other!

Ok, cool, affirmative on the reciprocal reviewing. I'm still very much getting used to github teamwork. Someone should write a book about it. Oh, wait.....

**Comment by sandreae** [comment]
In progress here : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/62

**Comment by sandreae** [comment]
Getting there ;-p
