### ISSUE TITLE
Move connect_all and get_ports to from pypatcher to jack_client_patching

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#33]
I think these to functions could be moved to jack_client_patching, what do you recon?

https://github.com/noiseorchestra/jacktrip_pypatcher/blob/02fef2513da49ae655f6536f3376529689a37a71/jacktrip_pypatcher.py#L31-L46

**Comment by sandreae** [comment]
This was done here : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/50

**Comment by madwort** [comment]
Nb. You can get these issues to autoclose by adding e.g. `Fixes #50`  to the description on a PR
