### ISSUE TITLE
Consistently use hold_music or lounge_music

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#40]
I think we use both `hold_music` and `lounge_music` to refer to the same thing - we should pick one and use it everywhere - I don't mind which (although `lounge` is more whimsical?)

**Comment by sandreae** [comment]
I think I fixed that here https://github.com/noiseorchestra/jacktrip_pypatcher/pull/32/commits/d37a532d5e3e93d9991cf0e168d6f9a2348d67d8 (not a well labelled commit though...). Went for `lounge` for exactly that reason ;-p
