### ISSUE TITLE
How to make pypatcher tests more meaningful

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#41]
While attempting https://github.com/noiseorchestra/jacktrip_pypatcher/pull/34 realised it was actually a bit more complicated than just moving the functions across because it effects where we instantiate various different classes and fetch client lists. Think it may as well happen as part of a larger refactoring, Trying to get my head round what's required for this. So far I have this:

- move remaining helper functions from pypatcher to relevant class objects (`connect_all` & `get_current_clients` => `jcp`)
- instantiate classes in `main()` and pass them into `autopatch()`
- get lists of ports in `main()` and set them as attributes on their relevant class instances (`all_jacktrip_receive_ports`, `all_ladspa_ports` etc...)
- make sure all class methods have appropriate `dry_run` responses, this might involve refactoring so that autopatch generates a list of connections before starting ladspa and disconnecting connections (this is something we wanted to try anyway).

This way we can instantiate dummy class objects with test values and pass them into the tests, which should spit out a lot of connecting and disconnecting information. Probably a list of ports to which it plans to connect, ladspa it will start/stop etc...

**Comment by madwort** [comment]
Yeah, there's two directions this can go, maybe we can do a bit of both! 

First one is to refactor the code to make it easier to test - this means things like breaking out testable functions from larger chunks of code. An example of this would be like creating `get_panning_positions`, which is easy to test: https://github.com/noiseorchestra/jacktrip_pypatcher/blob/trunk/test_ladspa_plugins.py  

The other thing is to start "mocking" things that have side-effects. I don't have time right now to create an example, but this looks like a good article on the subject: https://realpython.com/python-mock-library/ - in this case we could create a mock of  the `jackClient` object, then run various functions, and verify that our code has called the expected functions on the mock. Check it out!

**Comment by madwort** [comment]
(mocking is for testing our own code, so we are assuming that the jack library functions correctly as long as we give it the instructions that we think it should have)

**Comment by sandreae** [comment]
> Yeah, there's two directions this can go, maybe we can do a bit of both!
> 
> First one is to refactor the code to make it easier to test - this means things like breaking out testable functions from larger chunks of code. An example of this would be like creating `get_panning_positions`, which is easy to test: https://github.com/noiseorchestra/jacktrip_pypatcher/blob/trunk/test_ladspa_plugins.py
> 
> The other thing is to start "mocking" things that have side-effects. I don't have time right now to create an example, but this looks like a good article on the subject: https://realpython.com/python-mock-library/ - in this case we could create a mock of the `jackClient` object, then run various functions, and verify that our code has called the expected functions on the mock. Check it out!

Thanks, I will indeed check it out! (shouldn't be this week as I have tonnes of other stuff I should be doing, but you never know.....)

**Comment by sandreae** [comment]
Am I right thinking that one approach would be to create a mock of `jackClient` which returns dummy values when e.g. `get_ports` is called? This would be passed into `autopatch` while testing, pypatcher would happily run thinking it was interacting with a real `jackClient`, we get nice test results back.

**Comment by madwort** [comment]
yep that's the theory! I tried it last night, though, and there are complications with `Darkice` - we may need to mock that object seperately

**Comment by sandreae** [comment]
Think we're clear on this now so closing.
