### ISSUE TITLE
Distorted audio being sent back to clients

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#47]
Just finished another test session with 4 musicians and experienced a lot of audio distortion in the mix coming back from the server. It's hard to pinpoint *exactly* where it's happening, but it's fair to say we need more headroom. Apart from this the general audio quality was great and we didn't notice any latency issues. The session setup was as so:

locations: London, Manchester, Newcastle, Carmarthen
clients: 4 x musicians connecting with ANU
client jacktrip audio channels: some stereo, some mono

observations:
- mix returning from the server sounds distorted for clients
- happens when there are peaks in audio levels
- possibly happening more for the mono clients
- distortion NOT present to the same extent on the darkice recording
- the previously observed jacktrip glitch when dealing with peaking signals is observable on the recorded waveforms

![Screenshot from 2020-10-06 12-44-23](https://user-images.githubusercontent.com/24291662/95199811-56c34b80-07d5-11eb-9343-74da6e5a8263.png)
 
It seems the accumulation of signals into each client mix is causing distortion to occur when it's patched back into JackTrip to be sent back to the client. This is being exaggerated by the way that JackTrip (mis)handles the audio when peaks occur.

suggestions:
- drop the gain on all ladpsa ports (think this is quite simple to do)
- use the @madwort JackTrip branch which fixes distortion issues

**Comment by sandreae** [comment]
I can do a PR for the ladspa changes :+1:

**Comment by madwort** [comment]
the overflow fix just got merged into main jacktrip branch, should be in the next release (whenever that is)

**Comment by sandreae** [comment]
> the overflow fix just got merged into main jacktrip branch, should be in the next release (whenever that is)

Amazing!

**Comment by sandreae** [comment]
I think that only solves half of our issue though right? As in, we don't want it to peak in the first place...

**Comment by sandreae** [comment]
Worth saying that this would also be solved if everyone just turned down ;-p however in the session today it was again clear that it's hard to get that balance sometimes (and if you're the one with the strong signal, you won't hear the distortion in your mix), so probably good to minimise chances of this happening on the server. Good to know your thoughts on this too though as you have a deeper understanding of the JackTrip side of things.

**Comment by madwort** [comment]
> I think that only solves half of our issue though right? As in, we don't want it to peak in the first place...

yep yep

**Comment by sandreae** [comment]
> the overflow fix just got merged into main jacktrip branch, should be in the next release (whenever that is)

Also, whoop! #officialjacktripdev

**Comment by sandreae** [comment]
Closing because we have various solutions to explore, it's a semi-ongoing problem more related to use of the system than the system itself.

**Comment by madwort** [comment]
still no new upstream jacktrip release, I think - a bit annoying...! easy to roll our own for linux, but it would be good to have a new macOS client for people not yet on ANU...
