### ISSUE TITLE
Make loads more mocks and/or Reinstate dry_run mode

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#49]
* doesn't work correctly for several things:
  * stereo_recording
  * ladspa
  * ...probably more...

**Comment by sandreae** [comment]
Ah yeh, I can reinstate dry_run for now / for good.

stereo_recording done here : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/51

**Comment by sandreae** [comment]
ladspa done here : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/42/commits/956f959aaa280dcbb2748ea4815059ea72a4f20d

**Comment by sandreae** [comment]
darkice done here : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/52

**Comment by sandreae** [comment]
In [lounge_music](https://github.com/noiseorchestra/jacktrip_pypatcher/blob/trunk/lounge_music.py) do we need `dry_run` and `debug`? I know they have different functions, but maybe they can be combined in dry_run?

**Comment by sandreae** [comment]
Fairly sure dry_run will be fully reinstated when this PR is merged : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/61
