### ISSUE TITLE
Higher than expected Xruns with 4 + clients

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#74]
Experienced higher than expected jackd Xruns on a server which we would expect could easily handle 4+ clients (8 core, 16GB ram). After upgrading to 12 core 32GB ram system the issue seems to be resolved (however ideally things would work as expected at lower specs).

More investigation needed possible causes:
- issues with real-time priority for services (JACK, JackTrip, darkice etc...)
- ??

Will keep an eye on it and plan to test with a lower spec server again in the near future.

**Comment by madwort** [comment]
Any more details about what happened? Connection details of the clients (internet connection quality, jacktrip queue params etc)? xruns were observed on the server? was anything observed on the clients? presumably it was audible?

**Comment by madwort** [comment]
One thing is that the earlier sessions were on the earlier version of jacktrip (pre decoupling the threads from cores to allow more connections) - that could actually lead to more thread contention & poorer performance? Might be worth A-B testing with the older version of jacktrip?

**Comment by sandreae** [comment]
> Any more details about what happened? Connection details of the clients (internet connection quality, jacktrip queue params etc)? xruns were observed on the server? was anything observed on the clients? presumably it was audible?

Yeh, sure:

- all tests were run at 256pps.
- connections were coming from noiseaa4 server, so I had considered that there could be issues there running several clients, but as it cleared up after upgrading the server I guess that can't be the case.
- tried with gradually increasing q rates, went up to 20.
- Xruns were observed on the server
- Actually can't remember what was happening on the clients, I think there were Xruns there too (maybe because of missing packets from the server?). This could be tested again though as the system on noiseaa4 is still the same.
- Yep, audible, the usual background clicks and missed audio packets.

**Comment by sandreae** [comment]
> One thing is that the earlier sessions were on the earlier version of jacktrip (pre decoupling the threads from cores to allow more connections) - that could actually lead to more thread contention & poorer performance? Might be worth A-B testing with the older version of jacktrip?

Interesting, hadn't considered that. Hard to do an A-B test on noiseaa3 now cos it is beefed up and not showing any issues. As we use other servers I guess we can see if we observe this happening and then we could try the earlier JackTrip build.

**Comment by madwort** [comment]
Also observed this today on a 4 core machine running a trio session - will try bigger machines next time.

**Comment by madwort** [comment]
I suspect the `pypatcher_watchgod` service needs to also be run at a higher priority, in order for `jack_capture` and `ng-ladspa` to be run at higher priority.

**Comment by sandreae** [comment]
> I suspect the `pypatcher_watchgod` service needs to also be run at a higher priority, in order for `jack_capture` and `ng-ladspa` to be run at higher priority.

Ah, I just pulled these changes onto the server and went to change the `pypatcher_watchgod` service file and.... it already had real-time priority enabled (same as in the recent PR). I must have already tried this when the issue occured a while ago. So it looks like that wasn't the problem. Damn...

**Comment by madwort** [comment]
> > I suspect the `pypatcher_watchgod` service needs to also be run at a higher priority, in order for `jack_capture` and `ng-ladspa` to be run at higher priority.
> 
> Ah, I just pulled these changes onto the server and went to change the `pypatcher_watchgod` service file and.... it already had real-time priority enabled (same as in the recent PR). I must have already tried this when the issue occured a while ago. So it looks like that wasn't the problem. Damn...

Doh!! Well, good to have fixed it at least.

**Comment by madwort** [comment]
>  Xruns there too (maybe because of missing packets from the server?)

I /think/ missing packets shouldn't cause xruns - because xruns are when the jackd server runs a client callback and doesn't get a response in the time it requires - from my understanding jacktrip /should/ return a packet of silence in a timely fashion if there are missing packets, so network issues should be separate from xruns. However, there are some issues with jacktrip & it's possible that's wrong. 

The other thing is - what I observed was mostly xruns from jack clients other than jacktrip (ladspa and jack_capture in particular). Maybe it does just need more cpu & a realtime kernel.

**Comment by sandreae** [comment]
Yeh, I was watching the Jack server closely for soundcheck in the session last night, and when there were audible missed packets in the audio I didn't observe any xruns in the client or on the server. There were almost no Xruns in fact.

Not exactly related, but I also wasn't seeing the "udp missed packet" in the jacktrip output when I would normally expect it, maybe this message has been removed in the update? Seems strange though, cos that was quite useful to see.

**Comment by madwort** [comment]
Another thing I was looking at was - in `/etc/systemd/system.conf` and `/etc/systemd/user.conf` I'm currently setting `DefaultLimitMEMLOCK=128M`, wondering if I need to set `DefaultLimitRTPRIO` too.

**Comment by madwort** [comment]
> Yeh, I was watching the Jack server closely for soundcheck in the session last night, and when there were audible missed packets in the audio I didn't observe any xruns in the client or on the server. There were almost no Xruns in fact.

Good news - remind me what spec noiseaa3 is currently - is it 12-core? 

> Not exactly related, but I also wasn't seeing the "udp missed packet" in the jacktrip output when I would normally expect it, maybe this message has been removed in the update? Seems strange though, cos that was quite useful to see.

Yeah they have definitely changed some stuff of that output stuff recently.

**Comment by sandreae** [comment]
> > Yeh, I was watching the Jack server closely for soundcheck in the session last night, and when there were audible missed packets in the audio I didn't observe any xruns in the client or on the server. There were almost no Xruns in fact.
> 
> Good news - remind me what spec noiseaa3 is currently - is it 12-core?

Yeh, 12-core 32 GB RAM. It would be interesting to try varying the RAM vs CPUs balance to see if it changes the results we're getting. There are the High Memery Linode plans for example (24GB RAM 1-core).

**Comment by sandreae** [comment]
Here's the `top` output from the 12-core server running a pypatcher session with 8 client connections:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                   
 6376 sam       20   0 2606816  90904  89908 S 104.0  0.3   3:00.35 jacktrip                                                                  
 6414 sam       -5   0  313056  90032  87272 S   3.0  0.3  17:06.64 darkice                                                                   
 8648 sam       20   0  413612  86712  84672 S   1.7  0.3   0:03.48 jack_capture                                                              
 6375 sam       20   0  218596  93084  85972 S   1.3  0.3   4:42.93 jackd                                                                     
 8723 sam       20   0  178196  83984  83660 S   0.7  0.3   0:01.39 jackspa-cli                                                               
 8728 sam       20   0  178196  83912  83584 S   0.7  0.3   0:01.33 jackspa-cli                                                               
 8748 sam       20   0  178196  83992  83664 S   0.7  0.3   0:00.99 jackspa-cli                                                               
 8768 sam       20   0  178196  83964  83640 S   0.7  0.3   0:01.06 jackspa-cli                                                               
 8772 sam       20   0  178196  83884  83556 S   0.7  0.3   0:01.12 jackspa-cli                                                               
 8800 sam       20   0  178196  83816  83488 S   0.7  0.3   0:00.90 jackspa-cli                                                               
 8804 sam       20   0  178196  84012  83688 S   0.7  0.3   0:00.78 jackspa-cli                                                               
 8812 sam       20   0  178196  83980  83652 S   0.7  0.3   0:01.00 jackspa-cli                                                               
    7 root      20   0       0      0      0 S   0.3  0.0   0:00.48 ksoftirqd/0                                                               
```
and the jackd output:

```
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-06 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-left-15 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-15 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-left-60 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-60 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-07 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Nov 14 17:55:01 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = darkice was not finished, state = Triggered
Nov 14 17:55:01 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = jack_capture was not finished, state = Running
Nov 14 17:55:01 noiseaa3.miniserver.com jackd[6375]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = darkice was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = jack_capture was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-45 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-05 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-06 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-left-60 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-60 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-07 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
```


and the top output from the 2-core 2GB RAM server running the jacktrip clients connecting to the hub server:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                              
28383 sam       20   0  378896  90180  89536 S   5.7  4.4   1:03.91 jacktrip                                                             
28412 sam       20   0  378896  90016  89376 S   5.7  4.4   0:37.22 jacktrip                                                             
28441 sam       20   0  378896  90092  89452 S   5.7  4.4   0:33.20 jacktrip                                                             
28426 sam       20   0  378896  90180  89540 S   5.3  4.4   0:34.81 jacktrip                                                             
28469 sam       20   0  378896  90188  89548 S   5.3  4.4   0:30.09 jacktrip                                                             
28483 sam       20   0  378896  90104  89460 S   5.3  4.4   0:28.31 jacktrip                                                             
28398 sam       20   0  378896  90104  89460 S   5.0  4.4   0:41.49 jacktrip                                                             
28455 sam       20   0  378896  90204  89564 S   5.0  4.4   0:31.34 jacktrip                                                             
 1074 sam       20   0  218544  93104  85976 S   1.3  4.6 183:47.57 jackd                                                                
28300 sam       20   0  177092  84892  84432 R   1.0  4.2   0:05.95 mpg123.bin                                                           
28311 sam       20   0  177092  84892  84428 R   1.0  4.2   0:07.35 mpg123.bin                                                           
28322 sam       20   0  177092  84892  84428 S   1.0  4.2   0:06.30 mpg123.bin                                                           
28333 sam       20   0  177092  85068  84608 R   1.0  4.2   0:06.54 mpg123.bin                                                           
28355 sam       20   0  177092  84976  84516 S   1.0  4.2   0:06.01 mpg123.bin                                                           
28344 sam       20   0  177092  84928  84468 S   0.7  4.2   0:05.71 mpg123.bin                                                           
28366 sam       20   0  177092  84948  84484 S   0.7  4.2   0:05.56 mpg123.bin                                                           

```

**Comment by madwort** [comment]
Copying your realtime diagnostics tests results into this thread for reference!

---

== GUI-enabled checks ==
Checking if you are root... no - good
Checking filesystem 'noatime' parameter... 4.15.0 kernel - good
(relatime is default since 2.6.30)
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu10/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu8/cpufreq/scaling_governor: No such file or directory
cat: /sys/devices/system/cpu/cpu9/cpufreq/scaling_governor: No such file or directory
Checking CPU Governors... CPU 0: '' CPU 1: '' CPU 10: '' CPU 11: '' CPU 2: '' CPU 3: '' CPU 4: '' CPU 5: '' CPU 6: '' CPU 7: '' CPU 8: '' CPU 9: ''  - not good
Set CPU Governors to 'performance' with 'cpupower frequency-set -g performance' or 'cpufreq-set -c <cpunr> -g performance' (Debian/Ubuntu)
See also: http://linuxmusicians.com/viewtopic.php?f=27&t=844
Checking swappiness... 60 - not good
** vm.swappiness is larger than 10
Set swappiness by adding 'vm.swappiness=10' to /etc/sysctl.conf and rebooting

Checking for resource-intensive background processes... none found - good
Checking checking sysctl inotify max_user_watches... < 524288 - not good
increase max_user_watches by adding 'fs.inotify.max_user_watches = 524288' to /etc/sysctl.conf and rebooting
For more information, see http://wiki.linuxaudio.org/wiki/system_configuration#sysctlconf
Checking whether you're in the 'audio' group... yes - good
Checking for multiple 'audio' groups... no - good
Checking the ability to prioritize processes with chrt... yes - good
Checking kernel support for high resolution timers... found - good
Kernel with Real-Time Preemption... not found - not good
Kernel without 'threadirqs' parameter or real-time capabilities found
For more information, see https://wiki.linuxaudio.org/wiki/system_configuration#do_i_really_need_a_real-time_kernel
Checking if kernel system timer is high-resolution... found - good
Checking kernel support for tickless timer... found - good

**Comment by madwort** [comment]
we should at least do:
`increase max_user_watches by adding 'fs.inotify.max_user_watches = 524288' to /etc/sysctl.conf`

**Comment by madwort** [comment]
looking at your jackd sample output, this is three events, right?

```
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-06 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-left-15 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-15 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-left-60 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-60 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-07 was not finished, state = Triggered
Nov 14 17:45:36 noiseaa3.miniserver.com jackd[6375]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
```

```
Nov 14 17:55:01 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = darkice was not finished, state = Triggered
Nov 14 17:55:01 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = jack_capture was not finished, state = Running
Nov 14 17:55:01 noiseaa3.miniserver.com jackd[6375]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
```

```
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = darkice was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = jack_capture was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-45 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-05 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-06 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-left-60 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ladspa-right-60 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackEngine::XRun: client = ..ffff.37.128.131.59-07 was not finished, state = Triggered
Nov 14 17:55:11 noiseaa3.miniserver.com jackd[6375]: JackAudioDriver::ProcessGraphAsyncMaster: Process error
```

In terms of total number of jack clients - we should have four jacktrip clients, darkice, jack_capture and then eight jackspa-cli - a total of 14 jack clients. And in these three events we've got 6, 2, and 8 clients not finishing in time & causing an xrun. 

I guess one thing that's standing out to me is that we're using a lot more ladspa plugins with the new patching scheme compared to the previous one. Although they're using hardly any cpu when measured by cpu usage, they might be causing issues because of the burstiness - which is that on the jackd tick suddenly every plugin has to run at once, then there's a break where nothing has to run until the next jackd tick.

**Comment by madwort** [comment]
just re-read your original post - 8 clients! ok, so...

In terms of total number of jack clients - we should have 8 jacktrip clients, darkice, jack_capture and then 8 jackspa-cli - a total of 18 jack clients and 12 cores. And in these three events we've got 6, 2, and 8 clients not finishing in time & causing an xrun.

**Comment by sandreae** [comment]
> And I thought we had 8 jackspa-cli for 4 clients, clearly we've got 8 jackspa-cli for 8 clients, so that's not nearly so different.

Yeh, the new patching definitely uses more `ladspa` clients (2 or 3 more depending on odd/even connections), the main place this has an impact is in the first few connections (2 & 3 in particular) where before we used pure `left`, `right` and `center` to do almost everything. Once we get to higher client numbers it makes lass of a difference.

> looking at your jackd sample output, this is three events, right?
Yeh, looks like three discrete events. Maybe I didn't say when I posted, but the connection was super clear, I had to wait 10 mins just to see any Xruns, and I think the first ones in the above output might have been associated with a re-patch event. So the server we had seemed to be handling it ok.

**Comment by sandreae** [comment]
Does it make sense to you that JackTrip on the hub server is using 105% CPU but on the server running all 8 JackTrip clients it's only using (total of around) 50%?

**Comment by madwort** [comment]
> Does it make sense to you that JackTrip on the hub server is using 105% CPU but on the server running all 8 JackTrip clients it's only using (total of around) 50%?

Hmmmm, I hadn't spotted that. I don't know - if it was a p2p connection, and it was basically the same code running at either end, then I'd be more surprised if it was that different. But the hub server might be slighly different code on the server side vs the client side - e.g. it looks like it might be multi-threading the client threads in a different way to the way that running multiple client instances on the same machine does. Would need to do a deep dive on the JackTrip source code, I think, to get an idea of what might be going on...

**Comment by sandreae** [comment]
> > Does it make sense to you that JackTrip on the hub server is using 105% CPU but on the server running all 8 JackTrip clients it's only using (total of around) 50%?
> 
> Hmmmm, I hadn't spotted that. I don't know - if it was a p2p connection, and it was basically the same code running at either end, then I'd be more surprised if it was that different. But the hub server might be slighly different code on the server side vs the client side - e.g. it looks like it might be multi-threading the client threads in a different way to the way that running multiple client instances on the same machine does. Would need to do a deep dive on the JackTrip source code, I think, to get an idea of what might be going on...

Ok, yeh, I expect it's doing more than simply staring 8 independent clients, just thought I'd flag it up in case....

**Comment by madwort** [comment]
Throwing resources at it does seem to help - doing a Sloth Racket session right now on a DigitalOcean Dedicated CPU server with 16 cores & virtually no XRuns (like, one every 10-15mins)
