### ISSUE TITLE
Missing service file for mpg123?

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#79]
The docs say `systemctl enable mpg123.service`, but there's no file in the repo for that.

**Comment by sandreae** [comment]
Sorry, can't dig deep right now, but I'm pretty sure that's not needed cos we start and stop mpg123 when needed.

**Comment by madwort** [comment]
great thanks!

**Comment by madwort** [comment]
verified, not required.
