### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#85]
Now that I'm automating deployments, I'm going to need consistent versioning.... 
Are you familiar with https://semver.org/ @sandreae ? Can we start doing releases? Maybe we could just declare that the current state is `1.0.0` and go from there?

**Comment by sandreae** [comment]
Yep, sounds good, let's do this now before merging the next round of PRs.

**Comment by sandreae** [comment]
To check the correct procedure:

- we release from trunk
- tag: v1.0.0

**Comment by madwort** [comment]
yes, I think we should just have one trunk branch that we merge into & release immediately (rather than separate trunk/dev/etc branches).

the tag, I can never remember - at my old job some things had to be `1.0.0` and some things had to be `v1.0.0` and now I'm permanently confused about which is which. I /think/ the tag should be `1.0.0`, but if you have strong evidence from other python-ish repos then let me know!

**Comment by madwort** [comment]
e.g. https://github.com/spatialaudio/jackclient-python - tags are like `1.0.0`

**Comment by madwort** [comment]
Hmmm, although the github release page is all "consider using `v1.0.0`". I don't think it really matters.

**Comment by sandreae** [comment]
Ok, cool, I'll do one now with `1.0.0` then.

**Comment by sandreae** [comment]
https://github.com/noiseorchestra/jacktrip_pypatcher/releases/tag/1.0.0

Whoop!

**Comment by madwort** [comment]
🎉
