### ISSUE TITLE
lounge music not working

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#92]
Briefly had a test server running this evening to test Seth's setup - for some reason the lounge music didn't seem to be able to start correctly, although playing music manually from the command line did work... file for later testing...

**Comment by sandreae** [comment]
hmmmm, strange, it's worked fine on all the test servers I've had going this week (at least 6 or 7).

**Comment by madwort** [comment]
oh, I think it might have been me experimenting with jacktrip 1.3 before it was compatible...
