### ISSUE TITLE
Support jacktrip 1.3

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/jacktrip_pypatcher#93]
see https://github.com/madwort/jacktrip-server-automation/pull/7#issuecomment-773250548

**Comment by madwort** [comment]
> When I was testing out this release in it's beta version the JackTrip clients had been changed from ..ffff.192.168.0.1 to __ffff.192.168.0.1 which messed up our client selecting. This would just need updating in py_patcher and making a new release.

This will be v2, I guess?

**Comment by madwort** [comment]
unless we can find a way to make it compatible with both?

**Comment by sandreae** [comment]
I recon this will do it: https://github.com/noiseorchestra/jacktrip_pypatcher/pull/94

**Comment by madwort** [comment]
@sandreae could you do a v1.1 release then? then I can use the tag in the deployment repo!

**Comment by sandreae** [comment]
Yep, done :+1:

**Comment by madwort** [comment]
thanks!

**Comment by madwort** [comment]
reopening because of https://github.com/madwort/jacktrip-server-automation/pull/7#issuecomment-780459109

**Comment by madwort** [comment]
How shall we do this then @sandreae ? As far as I can see, options are:

* (a) support 1.2 & 1.3 - copy 1.3 to `/usr/bin` in my server automation scripts - I don't much fancy this option, as I prefer having stuff we've compiled ourselves in `/usr/local/bin`
* (b) support 1.2 & 1.3 - update pypatcher service file to `/usr/local/bin` and update the server automation scripts to use the new pypatcher with 1.2 & merge that before merging 1.3 (so that we can always check out an old revision of those scripts & to build a server with new pypatcher but 1.2)
* (c) support only 1.3 - update pypatcher service file to `/usr/local/bin` - we don't need 1.2 anymore, we're going forwards into the future!
* (d) ...another idea...

**Comment by sandreae** [comment]
I would say (c) cos I don't really see any situation where we would need to run pypatcher with v1.2 anymore. v1.3 is the official JackTrip version now I think, and even if clients are using older versions it isn't a problem. What do you recon?

**Comment by sandreae** [comment]
(in fact, maybe it's a healthy reminder to use the newest JT if everything breaks when you don't ;-p)

**Comment by madwort** [comment]
alrighty! https://github.com/noiseorchestra/jacktrip_pypatcher/pull/95
